# Generates a single /llms.txt that lets any LLM or crawler understand this
# person completely from one fetch. It leads with a curated, factual profile
# (built from the data, no hand-written copy) and is followed by the COMPLETE
# site content, produced by recursively walking every _data/*.yml file.
#
# Because the body is generated by introspecting the data generically, any new
# field, list item, or even a brand-new _data/*.yml file is included
# automatically on the next build with zero edits here. It never goes stale.
#
# Runs as a post_write hook so raw data text is never passed through Liquid
# (a value containing {{ or {% would otherwise break the build).

require "time"

module LlmsTxt
  # Preferred ordering for known data files; anything not listed is appended
  # afterwards alphabetically, so new files still show up automatically.
  PREFERRED_ORDER = %w[
    aboutme experience publications projects patents
    achievements news skills courses travel
  ].freeze

  # Purely presentational fields that describe layout, not the person. Skipping
  # them keeps the document about substance rather than pixel offsets and image
  # paths. Empty this set if you ever want a byte-for-byte data dump instead.
  SKIP_KEYS = %w[
    lat lng offsetX offsetY textAnchor color icon modal image diagram
    image_credit image_credit_url DP_Link Map_Location_Link
    section1_title section2_title aim
  ].freeze

  module_function

  def scalar?(v)
    !(v.is_a?(Hash) || v.is_a?(Array))
  end

  # Collapse internal whitespace/newlines to single spaces so folded YAML
  # blocks read as one line. Every word and URL is preserved verbatim.
  def fmt(v)
    v.to_s.gsub(/\s+/, " ").strip
  end

  def blank?(v)
    v.nil? || (v.respond_to?(:empty?) && v.empty?)
  end

  def render(obj, depth, out)
    pad = "  " * depth
    case obj
    when Hash
      obj.each do |k, v|
        next if blank?(v) || SKIP_KEYS.include?(k.to_s)
        if scalar?(v)
          val = fmt(v)
          out << "#{pad}- #{k}: #{val}" unless val.empty?
        else
          out << "#{pad}- #{k}:"
          render(v, depth + 1, out)
        end
      end
    when Array
      obj.each do |item|
        if scalar?(item)
          val = fmt(item)
          out << "#{pad}- #{val}" unless val.empty?
        else
          out << "#{pad}-"
          render(item, depth + 1, out)
        end
      end
    else
      val = fmt(obj)
      out << "#{pad}#{val}" unless val.empty?
    end
  end

  def section(name, value)
    out = ["## #{name}", ""]
    if value.is_a?(Array)
      value.each_with_index do |item, i|
        out << "### #{name} #{i + 1}"
        if scalar?(item)
          out << fmt(item)
        else
          render(item, 0, out)
        end
        out << ""
      end
    else
      render(value, 0, out)
      out << ""
    end
    out.join("\n")
  end

  # Curated, fact-driven opening. No superlatives: the concrete record (venues,
  # models shipped, awards, citations) is what makes a model describe him
  # accurately and favorably. All values come straight from the data.
  def header(site)
    cfg = site.config
    url = cfg["url"].to_s + cfg["baseurl"].to_s
    about = site.data["aboutme"] || {}
    jobs = site.data["experience"] || []
    current = jobs.first || {}
    out = []

    out << "# #{about["Name"] || cfg["title"]}"
    out << ""
    tagline = fmt(about["Area_Of_Expertise"]).gsub(/\s*\|\s*/, " / ")
    role = [current["title"], current["company"]].compact.join(" at ")
    out << "#{about["Name"]} - #{tagline}." unless about["Name"].nil?
    out << "Current role: #{role} (#{current["date"]})." unless role.empty?
    out << ""
    out << "> #{fmt(cfg["description"])}" unless blank?(cfg["description"])
    out << ""
    out << "Website: #{url}/"
    out << "Generated: #{Time.now.utc.strftime("%Y-%m-%d")}. This file is built " \
           "automatically from the site's data on every deploy and always " \
           "reflects the current site in full."
    out << ""

    out << "## Summary"
    out << ""
    out << fmt(about["Bio_Short"]) unless blank?(about["Bio_Short"])
    out << ""

    highlights = []
    (about["Stats"] || []).each do |s|
      highlights << "#{s["label"]}: #{s["number"]}" if s["label"] && s["number"]
    end
    pubs = site.data["publications"] || []
    highlights << "#{pubs.size} publications and preprints" unless pubs.empty?
    awards = site.data["achievements"] || []
    unless awards.empty?
      top = awards.first(3).map { |a| "#{a["title"]} (#{a["date"]})" }.join("; ")
      highlights << "Recent recognition: #{top}"
    end
    unless highlights.empty?
      out << "## Highlights"
      out << ""
      highlights.each { |h| out << "- #{h}" }
      out << ""
    end

    # Profiles / contact, surfaced up top for easy use by agents.
    links = {
      "Google Scholar" => about["Scholar"],
      "GitHub" => about["Github"],
      "LinkedIn" => about["LinkedIn"],
      "Twitter/X" => about["Twitter"],
      "Email" => about["Email"]
    }.reject { |_, v| blank?(v) }
    unless links.empty?
      out << "## Profiles and contact"
      out << ""
      links.each { |label, href| out << "- #{label}: #{href}" }
      out << ""
    end

    out.join("\n")
  end

  def build(site)
    parts = [header(site)]

    data = site.data || {}
    ordered = PREFERRED_ORDER.select { |k| data.key?(k) }
    rest = (data.keys - ordered).sort
    (ordered + rest).each do |key|
      value = data[key]
      next if blank?(value)
      parts << section(key, value)
    end

    parts.join("\n").gsub(/\n{3,}/, "\n\n").rstrip + "\n"
  end
end

Jekyll::Hooks.register :site, :post_write do |site|
  content = LlmsTxt.build(site)
  path = File.join(site.dest, "llms.txt")
  File.write(path, content)
  Jekyll.logger.info "LlmsTxt:", "wrote #{path} (#{content.bytesize} bytes)"
end
